version: "3"
services: 
  shopeetest:
    container_name: "docker-shopeeTest"
    restart: always
    build: .
    depends_on:
      - mysql
    environment:
     - DATABASE_HOST=mysql
    ports:
      - "3000:3000"
    expose:
      - "3000"
  mysql:
    container_name: mysql
    build: ./mysql
    restart: always
    ports:
      - "3001:3306"