version: "1"
services: 
  shopeeTest:
    container_name: "docker-shopeeTest"
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: shopeetest
    ports:
      - "3306:3306"